### ISSUE TITLE
Automatically create a user when new individual agent (person) is created.

### ISSUE THREAD

**Issue by numapanuma** [gopacifia/DEEP#29]
To automate the process of creating a user when an individual agent is created. Right now, you first create an agent, and then must create a user manually to let this agent sign in to the platform. It works this way because sensorica needed to create agent in their system that would never log in to the platform (say clients or suppliers). But in DEEP any individual agent will also be a user of the platform.

**Comment by escanda** [comment]
To maintain backwards compatibility to non participating agents (let's say a local carpenter who doesn't have yet an email account, silly example, but possible), when selecting a user agent of type Individual, two new fields will appear, a checkbox which when enabled will also enable an email field to invite the new user.

**Comment by numapanuma** [comment]
>  two new fields will appear, a checkbox which when enabled will also enable an email field to invite the new user.
So one field is the checkbox and the oter is the email field right?  
Great so we can merge this issue with issue #30 right?

**Comment by fosterlynn** [comment]
@numapanuma is it true that there will be no agents that are not outside the network?  Will people never need to show incoming resources from for example Amazon (or wherever)?

**Comment by escanda** [comment]
@numapanuma that's right, we now only need a warm template to welcome users :)

@fosterlynn I guess the most extended use case will be user agents, but I also think you made a point :+1:

**Comment by bhaugen** [comment]
You might want to look at https://github.com/gopacifia/DEEP/blob/master/valuenetwork/valueaccounting/views.py#L141

**Comment by escanda** [comment]
@bhaugen refactored a bit the create_user_agent view to make more use of django forms. there may be dragons :)

**Comment by bhaugen** [comment]
> there may be dragons :)

Deployed where? Got testers?
