### ISSUE TITLE
Automatic notifications by email to newly created user/agent

### ISSUE THREAD

**Issue by numapanuma** [gopacifia/DEEP#30]

**Comment by escanda** [comment]
Would we write a template for this email?

**Comment by numapanuma** [comment]
Just a first draft as for the welcome email template:

Welcome [name],
You have been invited by [inviting_agent_name] to be a member of the Democratic and Emancipatory Economic Platform (DEEP).

What to do next?
1. Log in with this username and password:
username: [username]
password: [password]
2. Follow the welcome guide to edit your profile, change your password and get to know how the platform works.
3. Start offering your products and services, and satisfy your needs thanks to the autonomous currencies available in your area.

[inviting_agent_name] will be your mentor during your familiarization process with the platform so you can ask him/her anything you couldn't answer through our user's documentation guide (link).

Enjoy all the new possibilities that this platform and the communities using it can offer you!

**Comment by bhaugen** [comment]
@escanda 
> Would we write a template for this email?

Yes. We're using the django-notification app, which unfortunately seems to have been abandoned under that name, although it still installs and works. It seems to have been renamed to pinax-notifications, and I think this doc mostly works:
https://pinax-notifications.readthedocs.io/en/latest/usage/

Here are some example notification templates:
https://github.com/gopacifia/DEEP/tree/master/valuenetwork/valueaccounting/templates/notification

You can find several examples of sending notifications in valueaccounting/views:
ctrl-f notification

**Comment by escanda** [comment]
@bhaugen finally upgraded to pinax-notifications (worked flawlessly) :)

@numapanuma changes are in the DEEP instance to be tested. Workflow is enabling the invite checkbox, setting the user email and saving the agent. The user will receive an email in which there will be an invite url. Once the user clicks on it, the user will be able to fill in its user information (username, password, etc).

**Comment by bhaugen** [comment]
@escanda , you're on a roll!
